
#include "gputypes/gputypes.h"
#include <stdio.h>

GPUType types[] = {
GPUTYPE_FLOAT, GPUTYPE_DOUBLE, GPUTYPE_HALF, GPUTYPE_BOOL, GPUTYPE_BYTE,
GPUTYPE_SHORT, GPUTYPE_INT, GPUTYPE_UNSIGNED_BYTE, GPUTYPE_UNSIGNED_SHORT,
GPUTYPE_UNSIGNED_INT,

GPUTYPE_FLOAT_VEC2, GPUTYPE_FLOAT_VEC3, GPUTYPE_FLOAT_VEC4,

GPUTYPE_FLOAT_MAT2, GPUTYPE_FLOAT_MAT3, GPUTYPE_FLOAT_MAT4,
GPUTYPE_FLOAT_MAT2x3, GPUTYPE_FLOAT_MAT2x4, GPUTYPE_FLOAT_MAT3x2,
GPUTYPE_FLOAT_MAT3x4, GPUTYPE_FLOAT_MAT4x2, GPUTYPE_FLOAT_MAT4x3,

GPUTYPE_DOUBLE_VEC2, GPUTYPE_DOUBLE_VEC3, GPUTYPE_DOUBLE_VEC4,

GPUTYPE_DOUBLE_MAT2, GPUTYPE_DOUBLE_MAT3, GPUTYPE_DOUBLE_MAT4,
GPUTYPE_DOUBLE_MAT2x3, GPUTYPE_DOUBLE_MAT2x4, GPUTYPE_DOUBLE_MAT3x2,
GPUTYPE_DOUBLE_MAT3x4, GPUTYPE_DOUBLE_MAT4x2, GPUTYPE_DOUBLE_MAT4x3,

GPUTYPE_HALF_VEC2, GPUTYPE_HALF_VEC3, GPUTYPE_HALF_VEC4,

GPUTYPE_HALF_MAT2, GPUTYPE_HALF_MAT3, GPUTYPE_HALF_MAT4, GPUTYPE_HALF_MAT2x3,
GPUTYPE_HALF_MAT2x4, GPUTYPE_HALF_MAT3x2, GPUTYPE_HALF_MAT3x4,
GPUTYPE_HALF_MAT4x2, GPUTYPE_HALF_MAT4x3,

GPUTYPE_BOOL_VEC2, GPUTYPE_BOOL_VEC3, GPUTYPE_BOOL_VEC4,

GPUTYPE_BYTE_VEC2, GPUTYPE_BYTE_VEC3, GPUTYPE_BYTE_VEC4,

GPUTYPE_SHORT_VEC2, GPUTYPE_SHORT_VEC3, GPUTYPE_SHORT_VEC4,

GPUTYPE_INT_VEC2, GPUTYPE_INT_VEC3, GPUTYPE_INT_VEC4,

GPUTYPE_UNSIGNED_BYTE_VEC2, GPUTYPE_UNSIGNED_BYTE_VEC3,
GPUTYPE_UNSIGNED_BYTE_VEC4,

GPUTYPE_UNSIGNED_SHORT_VEC2, GPUTYPE_UNSIGNED_SHORT_VEC3,
GPUTYPE_UNSIGNED_SHORT_VEC4,

GPUTYPE_UNSIGNED_INT_VEC2, GPUTYPE_UNSIGNED_INT_VEC3, GPUTYPE_UNSIGNED_INT_VEC4,

};

int main() {

    size_t num_types = sizeof(types) / sizeof(types[0]);

    for (size_t i = 0; i < num_types; ++i) {
        GPUType t = types[i];
        const char *name = gputype_typeName(t);
        GPUType basetype = gputype_typeBase(t);
        const char *basename = gputype_typeName(basetype);
        int vecsize = gputype_typeElements(t);
        int size = gputype_sizeof(t);

        printf("(0x%04zx) %s vecsize %d basetype %s bytes %d\n", t, name,
               vecsize, basename, size);
    }

    return 0;
}
